# 00-persistent-volumes.yaml — All PersistentVolumeClaims
# Deploy BEFORE any stateful workloads (Postgres, Redis)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telemetry-postgres-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
