apiVersion: v1
kind: ConfigMap
metadata:
  name: oan-ui-nginx-config
  namespace: default
data:
  default.conf: |
    server {
        listen 8081;
        root /usr/share/nginx/html;
        index index.html;

        location /api/ {
            proxy_pass http://oan-llm:80;
            proxy_set_header Host oan-llm;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 120s;
        }

        location /telemetry/ {
            proxy_pass http://telemetry-dashboard-service:3001;
            proxy_set_header Host telemetry-dashboard-service;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 120s;
        }

        location /action/ {
            proxy_pass http://telemetry-dashboard-service:3001;
            proxy_set_header Host telemetry-dashboard-service;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 120s;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oan-ui
  namespace: default
  labels:
    app: oan-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oan-ui
  template:
    metadata:
      labels:
        app: oan-ui
    spec:
      containers:
        - name: oan-ui
          image: kelvinprabhu/oan-ui-service:yaseen-version
          ports:
            - containerPort: 8081
          env:
            - name: VITE_API_URL
              value: ""
            - name: VITE_APP_TITLE
              value: "OAN Custom Web App"
            - name: VITE_DEFAULT_LANGUAGE
              value: "en"
            - name: VITE_JWT_AUDIENCE
              value: "oan-telemetry-dashboard"
            - name: VITE_JWT_ISSUER
              value: "http://minikube.local:30090/realms/oan-telemetry"
            - name: VITE_JWT_EXPIRY_DAYS
              value: "365"
            - name: VITE_BYPASS_AUTH
              value: "true"
            - name: VITE_ENABLE_TELEMETRY
              value: "true"
            - name: VITE_TELEMETRY_HOST
              value: ""
            - name: VITE_TELEMETRY_KEY
              value: "your-telemetry-api-key"
            - name: VITE_TELEMETRY_SECRET
              value: "your-telemetry-secret"
            - name: VITE_TELEMETRY_CHANNEL
              value: "oan-web-channel"
            - name: VITE_TELEMETRY_PRODUCT_ID
              value: "oan-ui"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: nginx-config
          configMap:
            name: oan-ui-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: oan-ui
  namespace: default
spec:
  selector:
    app: oan-ui
  ports:
    - port: 80
      targetPort: 8081
  type: LoadBalancer