apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-ui-keycloak
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry-ui-keycloak
  template:
    metadata:
      labels:
        app: telemetry-ui-keycloak
    spec:
      containers:
        # --- Keycloak ---
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0
          args: ["start-dev"]
          ports:
            - containerPort: 8090
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_HTTP_PORT
              value: "8090"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_PROXY
              value: "edge"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8090
            initialDelaySeconds: 30
            periodSeconds: 15

        # --- Telemetry Dashboard UI ---
        - name: telemetry-dashboard-ui
          image: kelvinprabhu/telemetry-dashboard-ui:latest
          ports:
            - containerPort: 8082
          env:
            - name: VITE_SERVER_URL
              value: "http://telemetry-processor:3000"
            - name: VITE_WATCHTOWER_BASE_URL
              value: "http://telemetry-dashboard-service:3001"
            - name: VITE_WATCHTOWER_JWT
              value: ""
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 10
---
# Expose UI externally
apiVersion: v1
kind: Service
metadata:
  name: telemetry-dashboard-ui
  namespace: default
spec:
  selector:
    app: telemetry-ui-keycloak
  ports:
    - port: 80
      targetPort: 8082
  type: LoadBalancer
---
# Expose Keycloak externally
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: default
spec:
  selector:
    app: telemetry-ui-keycloak
  ports:
    - port: 80
      targetPort: 8090
  type: LoadBalancer